* Fun repo

Small repo with fun stuff

* Project Euler
** DONE Problem 51 -- Prime Digit Replacements
#+begin_quote
By replacing the 1st digit of the 2-digit number *3, it turns out that six of the nine possible values: 13, 23, 43, 53, 73, and 83, are all prime.

By replacing the 3rd and 4th digits of 56**3 with the same digit, this 5-digit number is the first example having seven primes among the ten generated numbers, yielding the family: 56003, 56113, 56333, 56443, 56663, 56773, and 56993. Consequently 56003, being the first member of this family, is the smallest prime with this property.

Find the smallest prime which, by replacing part of the number (not necessarily adjacent digits) with the same digit, is part of an eight prime value family.
#+end_quote
*** Solution (In go?)

Generate primes.

Iterate trough them leaving only prime numbers with repeating digits (2>).

Since we want to have at least 8 variations, the repeating digit cannot be bigger than 1.
(d <= 9 - Family size)

Form masks and just try them all. Replace repeating digit with the other ones
and checking if the resulting number is prime.

The way I am doing it is not the final perfect solution, but it solves the
problem. Let /n/ be a prime number that repeats digit /d/, I am checking if
n[d'/d] is prime. But it may be the case that the solution comes from partial
substitution. E.g. if the number is /55***3/, maybe the solution comes from
replacing just to digits instead of three.


** DONE Problem 52 -- Permuted Multiples
#+begin_quote
It can be seen that the number, 125874 , and its double, 251748 , contain
exactly the same digits, but in a different order.
Find the smallest positive integer, /x/ , such that /2x/ , /3x/ , /4x/ ,
/5x/,and /6x/, contain the same digits.
#+end_quote

*** Solution -- works
Check that the string codification using primes are the same.

*** Nice insight in the discussion thread

The decimal representation of 1/7 has the desired property.
** DONE Problem 53 -- Combinatoric selections

#+begin_quote
How many, not necessarily distinct, values of C(n,k) for 1 <= n <= 100, are greater than one-million?
#+end_quote

*** Solution -- works

Facts used: n < m, C(n,k) < C(m,k)
Used pascals triangle, just computing until n/2, and replicating results: C(n, k) = C(n, n - k)
Also, p < q <= n/2 => C(n,p) < C(n,q)

*** No insights
** DONE Problem 54 -- Poker Game!
#+begin_quote
The file, poker.txt, contains one-thousand random hands dealt to two players. Each line of the file contains ten cards (separated by a single space): the first five are Player 1's cards and the last five are Player 2's cards. You can assume that all hands are valid (no invalid characters or repeated cards), each player's hand is in no specific order, and in each hand there is a clear winner.

How many hands does Player 1 win?
#+end_quote

*** Solution
Nothing much, define hands, winnin scores and compare them.

*** No insights

** DONE Problem 55 -- Lychrel Numbers

Take 47, reverse and add, 47+74 = 121, which is palindromic.

Not all numbers produce palindromes so quickly. For example:
349 + 943 = 1292
1292 + 2921 = 4213
4213 + 3124 = 7337

There are numbers that never produce palindromes following this process. Such
numbers are called Lychrel numbers.

Assume A1: all numbers are Lychrel until proven otherwise.

Assume A2: all numbers below 10.000 are either::
(1) to become a palindrome in less than 50 iterations
(2) no-one, with all the computing power that exists, has managed so far to map it to a palindrome.

Also, there are palindromic numbers that are themselves Lychrel numbers: e.x. 4994.

Q: How many Lychrel numbers are there below 10.000?

*** Brute Force
** DONE Problem 56 -- Bigest digit sum of a^b numbers.
Brute Force
** DONE Problem 57 -- Square Root convergents!

Square root of two can be decomposed in \(1 + \frac{1}{2+ \frac{1}{2+ ...}}\)

In the first one)thousand expansions, how many fractions contain a numerator with more digits than the denominator?

*** Solution

P_{0} = 1/2, P_{n+1} = 1 / 2 + P_{n}

We can compute it easily with function returning rationals (as natural pairs).
*** brute force
People in the comments talked about a different way of doing it.
I saw some of them approximating the solution.
** DONE Problem 58 -- Spiral Primes

Find the side of the spiral squere where there is a ratio less than 10 of prime numbers on the diagonals

*** Solution

Generate sequence of numbers in the diagonal.
I coulnd't come up with a close formula so I computed it.

1 -+2> 3 -+2> 5 -+2> 7 -+2> 9 -+4> 11 ...

so add 2 to the side every 5 numbers.

checking primality using a sieve (although I read something on the comments of using something else)

There is an algorithm Robin-Miller for primality test in a range of numbers, next time check that one.
** DONE XOR Decryption
Brute force, get whatever result has the most ocurrences of letter 'e'.
